[package]
name = "cute"
version = "0.2.0"
authors = ["araraloren <blackcatoverwall@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
